-- Jalankan di Supabase Dashboard → SQL Editor

create table if not exists public.guestbook (
    id bigint generated by default as identity primary key,
    name text not null,
    message text not null,
    attendance text not null check (attendance in ('hadir', 'tidak-hadir')),
    created_at timestamptz not null default now()
);

alter table public.guestbook enable row level security;

create policy "Siapa saja bisa membaca ucapan"
    on public.guestbook for select
    using (true);

create policy "Siapa saja bisa mengirim ucapan"
    on public.guestbook for insert
    with check (true);
